#+title: CS120 Lab *10* Section *4*
#+author: Heyan Huang
#+startup: beamer
#+latex_class: beamer
#+options: H:1 num:t toc:nil

* Hello Tower iLLuminati, 

I am sorry for what I have brought to confused us during last night's email and this mornings' one concerning about Emeth's TA part. I apologize for that. I never mean to attack Emeth at all, if she feels I was attacking, it is not my intention. 

I can be open-minded to consider this time Emeth's lie to be hers "trying to be considerate" good manner. But at the same time, I did still feel very bad about Tuesday's meeting and team environment, and I consider it was mainly Emeth's fault -- who is the team manager and who supposed to be able to handle this case well. 

I don't know if all of you guys consider this about the same way, but just as I mentioned to some friend earlier, in our culture, we believe there is a perfect god's mind live in every alive human beings, and I believe what you declared. So what happened during the 2.5 hours, I don't even try to think and be judgmental at all. But at the same time, please also try to understand my consideration for Emeth. I was kind enough to remind her about her influence because Tuesday's meeting exposed her weakness, and I want her to perform good and our department to be good as well if anything matters and affected. 

At this point, I can't consider Emeth to be a good team leader, but try not to make this too much a big deal, and also for my last year's sake, I can tolerant it. I will try my best to cooperate with all of us together, and I deserve all other team members to treat us in appropriate manner as well. 

I thought my mornings' email should be the last one, didn't realize there came two more. I don't think I will reply any more before meeting. Let's hope we make a good meet today.

thanks,
heyan

* Re: Team Meeting 3:30
Thompson, Emeth (thom5468@vandals.uidaho.edu)
Sent:	Thursday, November 06, 2014 10:15 AM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
Heyan,

Stop personally attacking me through email. Our senior design group has nothing to do with my TA position and your opinion of my personality or how it reflects on the CS department. If you want to discuss these things then you need to email me and not the whole group. I mentioned that if there are actions that I do that disrupt our ability to work together then tell me what those are. I can change how I interact with the group to enable a better working environment. Obviously, lying is something you have zero tolerance for and I will do my best to ensure that my communications are understood not thought of as lies. 

I did mention that you feel disrespected in my past email and I understand why. You are upset because you feel lied to, but the problem isn't that I lied to be malicious and make you feel left out. It was just a poor word choice. I said "the meeting was about 15 minutes" what I should have said and what I really meant was "we worked for about 15 minutes". Ranger and Matt worked later than everyone else and 2.5 hours only applies to them not the whole meeting. 

Again, please restrict your communication to the group to topics that relate to the project not to me personally.

Emeth Thompson

* Re: Team Meeting 3:30
Bailey, Paul (bail1806@vandals.uidaho.edu)
Sent:	Thursday, November 06, 2014 10:22 AM
To:	
Thompson, Emeth (thom5468@vandals.uidaho.edu); Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu)
Heyan and Emeth,

Relax, we are a team and we are all on track to meet our goals that have been outlined. There has obviously been some miscommunication among some members, which is understandable considering we have a larger team whose members have dramatically different lives and schedules. 

On a side note: Since this topic was mentioned below... In terms of our Software Engineering class a few semesters back, I do not agree that I did "very little work". However, I will agree that when comparing my contribution to that particular project during that semester, there were many other students who invested a much larger portion of their time into the project. So in comparison, I did less work than some others, but in no way did I do "very little work". I did do my part in that project, and I completed everything that I was tasked with for that project,  just as I am doing my part in this project. I am sure there is some point that Emeth was trying to make in bringing that up, and that is fine. I am not offended by it, I just wanted to clarify that portion since this has turned into a public document. 

Emeth and Heyan, you are both valuable members to the team. I really think that this has been a big misunderstanding. I am sure we can work out our differences and continue to make progress on this project. 

Paul.

* Hello Emeth,

I had bad personal experience towards lies, and I have absolutely zero tolerance towards lies ever since. And I hate to be in the situation being suspected that I lied when actually I didn't. And that was the reason your lie triggered all my seisitivity and bad feeling towards you yesterday. And from your reply, at least, you and I didn't run into the corner that without email record, each of us deny on everything, which is good news for us. At least as this point, I can calm down.

It was your fault on Tuesday as the project manager didn't notify the meeting and didn't remind me about the meeting through email, and the team member didn't offer any kind reminder neither. And your email and coldness on Tuesday did surprise me, and make me feel disrespected, and you seemed not realizing this fact yet, but we can discuss about it all together today. 

Emeth, please realize that as the only undergraduate TA in the CS department, you have deep and wide influence on students here. In the student's eyes, as the only undergraduate TA, you are the representive and influence of the department, please behave properly so that the department's reputation won't get damaged by you. 

I have no experience lied by any other classmates here in US so far yet rather than you. I never know that people, students, project managers can lie this way yet until yesterday. And that's the reason yesterday I couldn't calm down at all. Let's prepare and expect an effective and productive meeting today then to solve the problems. 

Heyan

* Re: Team Meeting 3:30
Thompson, Emeth (thom5468@vandals.uidaho.edu)
Sent:	Thursday, November 06, 2014 2:44 AM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
Well everybody, we got stuff to talk about tomorrow. 

For the record:
1) I did say that Ranger wouldn't check a posted schedule if we had one. My experience with Ranger has been that he prefers verbal interaction over emails and documents. If we are going to devote time and resources to a making a calendar then we need to be sure that it will get used. If it is not used then it just becomes more busy work that nobody has time for. 
2) I did say that Paul did not do very much work for our Software Engineering project and Paul will probably agree. I was telling Heyan this because I want everyone to contribute to this project. We are all very busy and I don't want anyone to end up having to do more than their fair share.
3) I did say the meeting was about 15 minutes. This was an exaggeration because the group was mostly unproductive for the first hour. Pretty much the only members who got anything done was Matt and Ranger and they were the ones who worked late. Paul and I were there till about 3:50 (im not sure the exact time we left). 15 minutes is literally a lie that was meant to reflect our productivity. From now on i will be more specific so that there isn't any confusion.
4) I do have an aggressive and superficial personality. Ranger refers to me as "cold-hearted" and this does not bother me. If there are specific things I do that are aggressive and cause disruption, then I want to hear about this because I'm probably not aware that I'm doing it.

What is important is that we resolve problems where the group is unable to work together in a respectful manner. I think we have had some misunderstandings, miscommunications, and a lack of organization. This has resulted in Heyan feeling disrespected and we should all do what is reasonable to resolve this. What is considered reasonable can be discussed tomorrow. If anyone else feels that another member of the group has been disrespectful then tomorrow is the day to talk about it. 

Emeth Thompson

* Hello Emeth, 

  When I received your email yesterday, once I finished my wiki page bio, I replied to you as soon as possible within 2 hours. I didn't hear back from you until today around 2:30pm after your compiler class, you stopped by the office and hurry to grab your water bottle and we chatted for about 5 minutes. You declared it was just a short meeting lasted around 15 minutes and I didn't feel too bad about it at that time. You refused to use Google calender because you felt Ranger is the one won't check it; And you insisted to send us email reminders because you need to remind Ranger any way. Then you asked me questions about my hearing, and which sounds I have difficulties, I answered overall in general I am OK, but subtle difference like th /f/ /tf/ I have some difficulty to differentiate and pronounce correctly. 
  
  I can't feel as comfortable any more when I talked to Matt in CSAC and received your email today. I can't imagine, as a american student, how could you possibly confuse 2.5 hours (from 2:30 to around 5:00pm according to Matt) to be 15 minutes? Just as I feel surprised yesterday receiving your email, your attitude in that email, you avoid reply to me through email and talked to me instead, your today's email completely ignoring yesterday's matter, and emphasize the "grades" and "reply to all on email" thing, all together does make me feel bad now. It feels like I haven't done anything and I don't deserve a good grade, and maybe I should be ignored or dismissed from this team. 
  
  Let's be frank and face it. You mentioned that during your software engineer class Paul seemed to be the one didn't do anything, I answered that as a sub-team Paul and I are OK, we don't have such a problem. 
  Since you lied on 2.5 hours, if you are actually talking about me, at least when you asked me to type the team contract when no other members have any assignments, as the only international in the team who may have difficulties on language part later on, I did it without any word; 
  on 10/23 team meeting, you declared to work on wiki page, Paul and I declared for GUI; GUI is due on 11/11, wiki was yesterday, and I showed you from my laptop on 10/31 Friday in CSAC when you entered that I was working on Qt creator GUI interface, I showed you the form I was working on with Josh and other students together in CSAC; But on yesterday's wiki due day, you made such a thing. 
  On 10/2 you and I spent 1 hour to review and make necessary contents and format updates on team contract in our office using my laptop and Emacs; on 10/3 you sent out email declared you changed document font size from 10pt to 12pt, and I ended up change it back to 11pt without sending emails; 
  As you talked to me having seen how efficient I used Emacs and org-mode for latex, you asked me to be the person responsible for the design documents. In the followed team meeting, I specified that I haven't taken software engineer in regular class, not that confident about document contents, and we as a team agreed that, we all are responsible for the contents, and I will be the person to integrate and organize them to be good latex documents, with review like you and I did  already for team contract, because by that time all you four will be berried with heavy duty compiler homework. 
  And I am ok that I will be dragged behind for project implementations when all you four have heavy compiler duties, and we plan to get only the GUI interface implementations ready without linking the button functionality. Assigned to be the secondary Lead Programmer in the contract, with the primary one Ranger will focus on his compiler, I will still be the primary responsible person for GUI interface implementations. 
  
  
  I may have listed too much already. Above all, I am the only person in CSAC who needs to start 3 mornings from 8:00am, and Matt was the only person among those I asked who was willing to exchange one hours with me so that on Thursday mornings I don't have to wake up early, and he and I don't have any say sorry issue. You lied or not, Paul and Ranger could still be the judge. Since when I talked to Matt today he mentioned "We don't like stay here in CSAC", I think I have 2 main concern/issue here:
  
1. On tomorrow's meeting, we need settle down this "Tuesday meeting time and reminder" thing. I don't like working in CSAC while having meeting neither. So we need discuss about this;
   
2. For Emeth only: 
I should have graduated this May already because Dr. Jeffery and I have 2 year oral graduation agreement but I was blocked by the department for one more year, together with my medical problems, just so that it will make other students (like international ph.d students) feel better because my cs master's degree without a CS undergraduate processed too well under this 4.5 to 5 years on average bachelor's degree environment. For the passed more than two years, I am mature enough to know clearly my goals, and I worked hard and can bear whatever situation the department have possibly cast on me. I appreciate that the department gives me the opportunity for TA for this fall semester. I expressed my expectation for next semester, but I wouldn't demand it, and it's up to the department to decide who they select for TAs. And to my understanding, you got this semester's one special section TA was only because your husband was willing to accompany you to stay on campus for one more year, and you may not qualify for the TA yet because you haven't even finish compiler yet. And it was you not your husband was because you are the superficial one and can be induced to behave the way they expect. 
Unless you are especially cultivated as a "spy" by the department to dismiss discrimination on international students signal, if that's the case, simply ignore my email, you will have your destination; Otherwise, you need pay attention to your personality. We have every reason to prevent yesterday's thing to happen, but it happened (we skipped one meeting during your compiler exam week; you all didn't appear in CSAC yesterday as regularly did; you all didn't offer email or phone call reminder; and you lied); as the project manager, I replied to your email yesterday, but you didn't reply; And you lied to me today with later on your email mentioned nothing about Tuesday's meeting. 
The only possible reason I can possibly think that you behavior so wired recently (say things on last Friday's meeting, make such an attitude yesterday, and lie to me today) is that you are very aggressive, and worked too hard just for a TA opportunity. I wondered why you can't figure out the questions your two female students have on Lab7 or Assignment 7, and needed your husband to help you out in CSAC the other day. Now I think I have the answer. Keep sending emails out for senior design course and registering Dr. Soule's Video Games and Evolution course doesn't necessarily guarantee an A nor your TA position, but by correcting your personality and stopping being superficial and practice more can help you go a long way. I just had a sorry from you recently, and I don't need that word any more. I state this out sincerely just for your own good. 


I never want to make anything a big deal, but your 2.5 hours lie to be 15 minutes did challenge my bottom line. Since Dr. Soule treats you especially well, I struggled whole evening ever since I read the email to think if I should state it out, should I or shouldn't I send out this email? If I did become very sensitive and did make it a too much big deal by the environmental force recently, like suddenly on this Tuesday's lab, there were several students trying so hard to make me behave ugly, if that's the case, please ignore the email and forgive me. 

Sincerely, 
Heyan

* Team Meeting 3:30
  Thompson, Emeth (thom5468@vandals.uidaho.edu)
  Sent:	Wednesday, November 05, 2014 3:44 PM
  To:	
  Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Thompson, Emeth (thom5468@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
  Hello Tower iLLuminati,
  
  Just a reminder we have a meeting tomorrow at 3:30. This meeting will be in Matt's office unless it is unavailable. During the meeting we will prepare a plan for the information we want to share during the design review. Though Bolden said we should just talk about the "big-picture" features, i think we still try to match our presentation to the grade sheet requirements. Ranger will be our presenter for the design review but we should all agree upon the content since its all of our grades.
  
  If someone is unable to make it to the meeting then please reply to all on this email. 
  
  Thank you,
  Emeth Thompson
  
* RE: Senior Design Meeting
  Huang, Heyan (heyanh@vandals.uidaho.edu)
  Sent:	Tuesday, November 04, 2014 8:10 PM
  To:	
  Thompson, Emeth (thom5468@vandals.uidaho.edu)
  Cc:	
  Brown, Matthew [matt2714@vandals.uidaho.edu]; Adams, Ranger [adam6860@vandals.uidaho.edu]; Bailey, Paul [bail1806@vandals.uidaho.edu]
  Hello Emeth, 
  
  I am sorry to say that I missed today's meeting without notification. This is my first time missed a meeting. As an "environmental-friendly" team, I hope later on if such things happen, a short one sentence email reminder could help, and hoping that later on whoever is missing or late, we could do the same thing. 
  
  Though you declared it's a short meeting, the statement and attitude about the meeting contents still surprised me a little bit. I am currently working on the GUI Qt Creator Interface as we have assigned about a week ago, and I will meet Paul to discuss and finish our subteam's GUI design and documentation. Since Paul has added the GUI image into wiki already, I simply added my little bio-:)
  
  By the way, are we suppose to meet this Thursday for our team member meeting, or it's always consistent on Tuesday afternoon at 2:30 (and I need to stay in CSAC from 2:30-3:30 on Tuesday, but available on Thursday 2:30-3:30, as you already knows)? And later on if we do use the 2:30-3:30 Tuesday one hour, I hope we can do it in CSAC, or we find some other hour so that I can join. 
  
  thanks,
  Heyan
  
* Hello Emeth, 
  
  I am sorry to say that I missed today's meeting without notification. This is my first time missed a meeting. As an "environmental-friendly" team, I hope later on if such things happen, a short one sentence email reminder could help, and hoping that later on whoever is missing or late, we could do the same thing. 
  
  Though you declared it's a short meeting, the statement and attitude about the meeting contents still surprised me a little bit. I am currently working on the GUI Qt Creator Interface as we have assigned about a week ago, and I will meet Paul to discuss and finish our subteam's GUI design and documentation. Since Paul has added the GUI image into wiki already, I simply added my little bio-:)
  
  By the way, are we suppose to meet this Thursday for our team member meeting, or it's always consistent on Tuesday afternoon at 2:30 (and I need to stay in CSAC from 2:30-3:30 on Tuesday, but available on Thursday 2:30-3:30, as you already knows)? And later on if we do use the 2:30-3:30 Tuesday one hour, I hope we can do it in CSAC, or we find some other hour so that I can join. 
  
  thanks,
  Heyan
  
* Senior Design Meeting
  Thompson, Emeth (thom5468@vandals.uidaho.edu)
  Sent:	Tuesday, November 04, 2014 6:10 PM
  To:	
  Huang, Heyan (heyanh@vandals.uidaho.edu)
  Cc:	
  Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
  Hello Heyan,
  
  Today for senior design we had a short meeting where we cleared up some confusion about the GUI design. The grid which is the main work area will be static. i.e. it will not move and all squares in the grid will always show. The frame, which represents the light shows display area will be a movable object. In Paul's GUI design the grid is the gray squares and the frame is the orange squares. When the project is complete, the user will be able to fill in the grid however they want and they will use the frame to capture sections of the grid as frames in the light show.  
  
  Also, we all need to write a short bio for ourselves to put on our project's wiki page:
  
  http://mindworks.shoutwiki.com/wiki/Tower_Lights_Animator
  
  If you would like to edit your bio yourself then you should make an account at the wiki and edit the table listed under the  Team Members section. If you would rather me edit it then please reply to this email with the bio you would like to include. 
  
  Emeth Thompson
  
